version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.11.1
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install --user tox

fetch_data: &fetch_data
  run:
    name: Set script permissions and fetch data
    command: |
      

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/Sale-Price-House-Prediction/sale-price-house-prediction-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Running app tests
          command: |
            tox

  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: npm install -g @railway/cli
      - run:
          name: Deploy to Railway App
          command: |
            cd sale-price-house-prediction-api && railway up --detach --service sale-price-house-api

  test_and_upload_sale_price_house_prediction_model:
    <<: *defaults
    working_directory: ~/project/Sale-Price-House-Prediction/model-package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Fetch the data
          command: |
            tox -e fetch_data
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model to Gemfury
          command: |
            tox -e publish_model

tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 1
  deploy_pipeline:
    jobs:
      - test_app
      - deploy_app_to_railway:
          requires:
            - test_app
          filters:
            branches:
              only:
                - ci/cd
      - test_and_upload_sale_price_house_prediction_model:
          <<: *tags_only